version: "3.3"
services:
  api:
    container_name: "go-core"
    build: "./"
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27100:27017"
